# Generated by Django 4.0 on 2022-09-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='library_app.book')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('library_app.book', models.Model),
        ),
    ]
