# Generated by Django 4.0 on 2023-09-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('library_app', '0004_book_status_delete_issuedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
